# secrets.toml

# Sua chave da API OpenAI
OPENAI_API_KEY = "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"

# Assistant OpenAI
OPENAI_ASSISTANT = "asst_qgX5Ew0hCbZM0U2Bf0it7dbV"

[passwords]
# Follow the rule: username = "password"
admin = "oiticica"
